### ISSUE TITLE
Implement properties and children for SegmentNode

### ISSUE THREAD

**Issue by francescomari** [francescomari/jackrabbit-oak#11]
`SegmentNode` should have the following properties.

- `id`
- `version`
- `type`
- `info`
- `timestamp`

Moreover, it should expose child nodes for references and records.

**Comment by mduerig** [comment]
for id: https://github.com/francescomari/jackrabbit-oak/pull/12

**Comment by mduerig** [comment]
The other properties seem more involved as those are not available from `SegmentArchiveEntry`.

**Comment by mduerig** [comment]
Ack, the time stamp from the segment info should be sufficient.

**Comment by francescomari** [comment]
Every property, with the exception of `timestamp`, are implemented in 43fca31d04.

**Comment by mduerig** [comment]
Thanks. Consuming it here: https://github.com/mduerig/oak-tooling-api/commit/b24508aacb470f826846a1b1de102acd86d824cd

**Comment by francescomari** [comment]
I implemented the segment references in 6b50452861. Examples of usages are in the tests and in the commit message.

**Comment by francescomari** [comment]
I implemented the records in 34efc08faa. Examples of usages are in the tests and in the commit message.
